Final version of mint clone
misselliev/mintClone-microverse pull request #1
Opened 2019-01-15 23:52 UTC by misselliev

Please review our submission.

2019-01-19 06:10 UTC, rvvergara commented
Hi Santiago and Elizabeth,

Your mint signup form looks so good! :) Please just work on the following then submit another code review request:

1. Kindly create a README file and make sure your it has:
 - The project name (you can be creative for this name)
 - Short description of the project
 - Your names and links to your github profiles (for guidance on how to include links in markdown, which is used in README.md files, please visit https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
 - A link to your live demo. A tool we use is https://raw.githack.com. 

2. Please use https://validator.w3.org/#validate_by_input to validate your index.html. When I ran it there, it returned a number of errors. Upon running your index.html there and seeing the errors kindly edit accordingly. For instance you made a <div> tag as a child to a <span> tag. Please note that a <span> is an inline element and is used for purposes such as styling a part of a sentence (for instance, one word should be bigger) and which change occurs "inline". <div>, in contrast is a container for a block of code. Also, you have two divs with the same id <div id="create-text"> in line 42 and <div id="create-text"> in line 45. The `id` attribute's value can only be used in a unique element in your whole index.html file. If what you intended was to make sure the div in line 42 to have the same style as that in line 45 you should just use `class`.

Running your code in the validator will reveal all the things you need to change. 

3. In your styles.css I notice:

- you declared ` font-family: "AvenirNext", Avenir, "Helvetica Neue", Helvetica, Arial, sans-serif;` in lines 36, 50, 66, 108, 119 and 165 but you declared
` font-family: AvenirNext, Avenir, "Helvetica Neue", Helvetica, Arial, sans-serif;` in line 195. As far as I know, if declaring a typeface name you only use "" if the name of the typeface has two separate words. In this case the declaration you did in line 195 is the correct way to do this, so please correct the 6 lines I mentioned.

- in relation to this, you are using that exact same font-family for 7 different elements, I suggest just declaring a class for this so that you eliminate the repetion.

- the same is true for `font-size: 12px` which you declared 7 times in 7 different elements. I also suggest you either create a class for this or do group together those selectors for which this font-size is a style and select them together (separated by commas), so that you will only have one line that says `font-style: 12px`

2019-01-20 06:18 UTC, misselliev commented
Thank you for the feedback Ryan! I submitted the changes needed. I'll submit the code review form again.

2019-01-20 08:48 UTC, rvvergara commented
You are very much welcome! :)

2019-01-21 19:38 UTC, talihomz requested changes
Hi @misselliev @stiakov 

As @rvvergara  had noted earlier on, great job cloning the Intuit signup page! It really looks close to the  actual page.

I've added some comments to your code on what we can improve. Let me know if it makes sense so far.

2019-01-21 19:38 UTC, talihomz commented on index.html
> +  <script src="main.js"></script>
Move this to the bottom of the `body` section, just before the `</body> tag.

2019-01-21 19:38 UTC, talihomz commented on index.html
> +    <div style="padding: 20px 0px 20px 0px">
Always try and avoid inline styles as much as possible. Move this into your CSS files and use it here as a class.

2019-01-21 19:38 UTC, talihomz commented on index.html
> +        <i class="material-icons" style="text-decoration: none; color: white; font-size: 18px; line-height: 16px">lock</i>&nbsp;&nbsp;
Same as previous comment. Avoid inline styles in your markup.
I know styling `i` elements can be tricky! One approach would be to wrap this inside a `span`, then styling that instead. e.g.
`<span class="icon"><i class="material-icons">lock</i></span>`.

Then, add the style to `.icon` class.

2019-01-21 19:38 UTC, talihomz commented on index.html
> +        Invisible reCAPTCHA by Google <a href="#" class="link-deco-footer" style="font-size: 10px">Privacy Policy</a>
Avoid inline style. Move this to your CSS file

2019-01-21 19:38 UTC, talihomz commented on index.html
> +    <div class="link-deco letter-size" style="text-decoration: none">
Inline style here as well.

2019-01-22 16:37 UTC, merged

2019-01-25 10:06 UTC, talihomz commented
Awesome work on this! 

Though you merged it before the final thumbs up! 🙁